var nombre;
var apellido;
var edad;
var fechaDeNacimiento;
var direccion;
nombre='Caro';
apellido='Amarillo';
edad= 21;
fechaDeNacimiento='16.05.96';
direccion='Pedro de Mendoza 511';
console.log(nombre);
console.log(apellido);
console.log(edad);
console.log(fechaDeNacimiento);
console.log(direccion);