const nombre;
const apellido;
const edad;
const fechaDeNacimiento;
const direccion;
nombre='Caro';
apellido='Amarillo';
edad= 21;
fechaDeNacimiento='16.05.96';
direccion='Pedro de Mendoza 511';
console.log('Nombre:',nombre);
console.log('Apellido:',apellido);
console.log('Edad:',edad);
console.log('Fecha de Nacimiento:',fechaDeNacimiento);
console.log('Direccion:',direccion);